### ISSUE TITLE
how to stop a stream from server

### ISSUE THREAD

**Issue by cafefars** [JamiePhonic/rtmp-hls-stunnel#1]
Hello
If someone is sending a stream to the server
How can it be stopped from the server?
For example, we only know that the stream key is "test12345"

**Comment by JamiePhonic** [comment]
Hi @cafefars,

Add a couple of blank lines in `nginx.conf` after line 24 (`#push rtmp://localhost:1936/rtmp/<stream_key>; `) and add the following lines:
```
# Allow publish only specified IP
allow publish 127.0.0.1;
allow publish xxx.xxx.xxx.xxx;
deny publish all;
```
Replace `xxx.xxx.xxx.xxx` with the IP address of the computer you'd like to be able to stream to the server from.
You can add as many `allow publish xxx.xxx.xxx.xxx;` lines as you like for different computers.

Alternativley, on line 17 (`application live {`), change the word `live` to something else.
For example: `application my_live_stream {`
You would then change the address in your streaming application (OBS, etc) to match.
For example: `rtmp://<server ip>:1935/my_live_stream`

Make sure to restart the container after you've saved the config to apply the changes.

**Comment by JamiePhonic** [comment]
Updated Nginx configs to fix this in #bed56d5
By Default, only hosts with private IP's will be able to stream to the server.

**Comment by cafefars** [comment]
Thanks for the reply

The problem is when I do not know the IP of the stream sender

**Comment by JamiePhonic** [comment]
Unfortunatley the RTMP module does not implement any kind of native authentication and receiving a stream from across the internet is not really the intended use for this container.

The easiest option would be to "scramble" the application name. (make it a long random string for example)

In `nginx.conf`,On line 17 (`application live {`), change the word `live` to something else. 
For example: `application my_live_stream {`
You would then change the address in your streaming application (OBS, etc) to match.
For example: `rtmp://<server ip>:1935/my_live_stream`

Make sure to restart the container after you've saved the config to apply the changes.
