### ISSUE TITLE
Container nginx html to host assets path

### ISSUE THREAD

**Issue by westindiantech** [JamiePhonic/rtmp-hls-stunnel#6]
Hi, how can I map the nginx html directory to the host assets path?

I only see configs, players, ssl in the assets path on my host machine.

**Comment by JamiePhonic** [comment]
Hi @westindiantech ,

The "players" directory is a sub directory in the nginx HTML directory. its symlinked at runtime (line 34 of the `run.sh` entrypoint script)
`ln -sf /assets/players /usr/local/nginx/html/`

If you wanted to mount the actual root html directory, you could add an additional volume argument to do so:
`-v /your/local/assets/html:/usr/local/nginx/html`

Hope that helps

**Comment by westindiantech** [comment]
Okay thanks much
