### ISSUE TITLE
minimal config issue

### ISSUE THREAD

**Issue by Sokoloft** [JamiePhonic/rtmp-hls-stunnel#7]
Hello,

Initially when I had tried the container. It just crashed when I'd start it.

I was trying to use the minimal config. If I commented out the following nginx works as expected.

```
#listen [::]:1935;
```

Is it something I'm doing wrong or forgetting? Or something that was left in the minimal config by accident?

Thanks.

**Comment by JamiePhonic** [comment]
Thanks for pointing this out. 
Fixed build will be available on dockerhub shortly.
